name: LustrousLib
version: '${project.version}'
main: org.lustrouslib.LustrousLib
api-version: 1.20
authors: [ PureTrippH ]
description: A Utility Library for Many of the Plugins made by PureTrippH
website: github.com/PureTrippH
